first_name = input("What is your first name?")
last_name = input("What is your last name?")
email_address = input("What is your email?")
phone_number = input("What is your phone number?")
job_title = input("What is your job title?")
id_number = input("What is your ID number?")
print(f"{last_name.upper()}, {first_name}")
print(f"{email_address.title()}")
print(f"{job_title.title()}")
print(f"ID: {id_number}")
print(f"{phone_number}")
